version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: PicShare-wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/themes/PicShare
    depends_on:
      - db
    networks:
      - PicShare-network

  db:
    image: mysql:8.0
    container_name: PicShare-mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - PicShare-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PicShare-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
    networks:
      - PicShare-network

volumes:
  wordpress_data:
  db_data:

networks:
  PicShare-network:
    driver: bridge